<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.EmojiChatMessage</code>
 */
class EmojiChatMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>int64 emojiId = 3;</code>
     */
    protected $emojiId = 0;
    /**
     * Generated from protobuf field <code>.douyin.Text emojiContent = 4;</code>
     */
    protected $emojiContent = null;
    /**
     * Generated from protobuf field <code>string defaultContent = 5;</code>
     */
    protected $defaultContent = '';
    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 6;</code>
     */
    protected $backgroundImage = null;
    /**
     * Generated from protobuf field <code>bool fromIntercom = 7;</code>
     */
    protected $fromIntercom = false;
    /**
     * Generated from protobuf field <code>bool intercomHideUserCard = 8;</code>
     */
    protected $intercomHideUserCard = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\Common $common
     *     @type \app\protobuf\douyin\User $user
     *     @type int|string $emojiId
     *     @type \app\protobuf\douyin\Text $emojiContent
     *     @type string $defaultContent
     *     @type \app\protobuf\douyin\Image $backgroundImage
     *     @type bool $fromIntercom
     *     @type bool $intercomHideUserCard
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \app\protobuf\douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \app\protobuf\douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @return \app\protobuf\douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @param \app\protobuf\douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 emojiId = 3;</code>
     * @return int|string
     */
    public function getEmojiId()
    {
        return $this->emojiId;
    }

    /**
     * Generated from protobuf field <code>int64 emojiId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEmojiId($var)
    {
        GPBUtil::checkInt64($var);
        $this->emojiId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Text emojiContent = 4;</code>
     * @return \app\protobuf\douyin\Text|null
     */
    public function getEmojiContent()
    {
        return $this->emojiContent;
    }

    public function hasEmojiContent()
    {
        return isset($this->emojiContent);
    }

    public function clearEmojiContent()
    {
        unset($this->emojiContent);
    }

    /**
     * Generated from protobuf field <code>.douyin.Text emojiContent = 4;</code>
     * @param \app\protobuf\douyin\Text $var
     * @return $this
     */
    public function setEmojiContent($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Text::class);
        $this->emojiContent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string defaultContent = 5;</code>
     * @return string
     */
    public function getDefaultContent()
    {
        return $this->defaultContent;
    }

    /**
     * Generated from protobuf field <code>string defaultContent = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->defaultContent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 6;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getBackgroundImage()
    {
        return $this->backgroundImage;
    }

    public function hasBackgroundImage()
    {
        return isset($this->backgroundImage);
    }

    public function clearBackgroundImage()
    {
        unset($this->backgroundImage);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 6;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setBackgroundImage($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->backgroundImage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool fromIntercom = 7;</code>
     * @return bool
     */
    public function getFromIntercom()
    {
        return $this->fromIntercom;
    }

    /**
     * Generated from protobuf field <code>bool fromIntercom = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromIntercom($var)
    {
        GPBUtil::checkBool($var);
        $this->fromIntercom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool intercomHideUserCard = 8;</code>
     * @return bool
     */
    public function getIntercomHideUserCard()
    {
        return $this->intercomHideUserCard;
    }

    /**
     * Generated from protobuf field <code>bool intercomHideUserCard = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIntercomHideUserCard($var)
    {
        GPBUtil::checkBool($var);
        $this->intercomHideUserCard = $var;

        return $this;
    }

}

