<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * from https://github.com/HaoDong108/DouyinBarrageGrab/blob/main/BarrageGrab/proto/message.proto
 *
 * Generated from protobuf message <code>douyin.FansclubMessage</code>
 */
class FansclubMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common commonInfo = 1;</code>
     */
    protected $commonInfo = null;
    /**
     * 升级是1，加入是2
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>.douyin.User user = 4;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\Common $commonInfo
     *     @type int $type
     *           升级是1，加入是2
     *     @type string $content
     *     @type \app\protobuf\douyin\User $user
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common commonInfo = 1;</code>
     * @return \app\protobuf\douyin\Common|null
     */
    public function getCommonInfo()
    {
        return $this->commonInfo;
    }

    public function hasCommonInfo()
    {
        return isset($this->commonInfo);
    }

    public function clearCommonInfo()
    {
        unset($this->commonInfo);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common commonInfo = 1;</code>
     * @param \app\protobuf\douyin\Common $var
     * @return $this
     */
    public function setCommonInfo($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Common::class);
        $this->commonInfo = $var;

        return $this;
    }

    /**
     * 升级是1，加入是2
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * 升级是1，加入是2
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 4;</code>
     * @return \app\protobuf\douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 4;</code>
     * @param \app\protobuf\douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\User::class);
        $this->user = $var;

        return $this;
    }

}

