<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.FansClubData</code>
 */
class FansClubData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string clubName = 1;</code>
     */
    protected $clubName = '';
    /**
     * Generated from protobuf field <code>int32 level = 2;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>int32 userFansClubStatus = 3;</code>
     */
    protected $userFansClubStatus = 0;
    /**
     * Generated from protobuf field <code>.douyin.UserBadge badge = 4;</code>
     */
    protected $badge = null;
    /**
     * Generated from protobuf field <code>repeated int64 availableGiftIds = 5;</code>
     */
    private $availableGiftIds;
    /**
     * Generated from protobuf field <code>int64 anchorId = 6;</code>
     */
    protected $anchorId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $clubName
     *     @type int $level
     *     @type int $userFansClubStatus
     *     @type \app\protobuf\douyin\UserBadge $badge
     *     @type int[]|string[] $availableGiftIds
     *     @type int|string $anchorId
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string clubName = 1;</code>
     * @return string
     */
    public function getClubName()
    {
        return $this->clubName;
    }

    /**
     * Generated from protobuf field <code>string clubName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClubName($var)
    {
        GPBUtil::checkString($var, True);
        $this->clubName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 level = 2;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 userFansClubStatus = 3;</code>
     * @return int
     */
    public function getUserFansClubStatus()
    {
        return $this->userFansClubStatus;
    }

    /**
     * Generated from protobuf field <code>int32 userFansClubStatus = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserFansClubStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->userFansClubStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.UserBadge badge = 4;</code>
     * @return \app\protobuf\douyin\UserBadge|null
     */
    public function getBadge()
    {
        return $this->badge;
    }

    public function hasBadge()
    {
        return isset($this->badge);
    }

    public function clearBadge()
    {
        unset($this->badge);
    }

    /**
     * Generated from protobuf field <code>.douyin.UserBadge badge = 4;</code>
     * @param \app\protobuf\douyin\UserBadge $var
     * @return $this
     */
    public function setBadge($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\UserBadge::class);
        $this->badge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 availableGiftIds = 5;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getAvailableGiftIds()
    {
        return $this->availableGiftIds;
    }

    /**
     * Generated from protobuf field <code>repeated int64 availableGiftIds = 5;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setAvailableGiftIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->availableGiftIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 anchorId = 6;</code>
     * @return int|string
     */
    public function getAnchorId()
    {
        return $this->anchorId;
    }

    /**
     * Generated from protobuf field <code>int64 anchorId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnchorId($var)
    {
        GPBUtil::checkInt64($var);
        $this->anchorId = $var;

        return $this;
    }

}

