<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.FansClub</code>
 */
class FansClub extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.FansClubData data = 1;</code>
     */
    protected $data = null;
    /**
     * Generated from protobuf field <code>map<int32, .douyin.FansClubData> preferData = 2;</code>
     */
    private $preferData;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\FansClubData $data
     *     @type array|\Google\Protobuf\Internal\MapField $preferData
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.FansClubData data = 1;</code>
     * @return \app\protobuf\douyin\FansClubData|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.douyin.FansClubData data = 1;</code>
     * @param \app\protobuf\douyin\FansClubData $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\FansClubData::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<int32, .douyin.FansClubData> preferData = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPreferData()
    {
        return $this->preferData;
    }

    /**
     * Generated from protobuf field <code>map<int32, .douyin.FansClubData> preferData = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPreferData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \app\protobuf\douyin\FansClubData::class);
        $this->preferData = $arr;

        return $this;
    }

}

