<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.GiftIMPriority</code>
 */
class GiftIMPriority extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint64 queueSizesList = 1;</code>
     */
    private $queueSizesList;
    /**
     * Generated from protobuf field <code>uint64 selfQueuePriority = 2;</code>
     */
    protected $selfQueuePriority = 0;
    /**
     * Generated from protobuf field <code>uint64 priority = 3;</code>
     */
    protected $priority = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[] $queueSizesList
     *     @type int|string $selfQueuePriority
     *     @type int|string $priority
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint64 queueSizesList = 1;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getQueueSizesList()
    {
        return $this->queueSizesList;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 queueSizesList = 1;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setQueueSizesList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->queueSizesList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 selfQueuePriority = 2;</code>
     * @return int|string
     */
    public function getSelfQueuePriority()
    {
        return $this->selfQueuePriority;
    }

    /**
     * Generated from protobuf field <code>uint64 selfQueuePriority = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSelfQueuePriority($var)
    {
        GPBUtil::checkUint64($var);
        $this->selfQueuePriority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 priority = 3;</code>
     * @return int|string
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Generated from protobuf field <code>uint64 priority = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkUint64($var);
        $this->priority = $var;

        return $this;
    }

}

