<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.GradeIcon</code>
 */
class GradeIcon extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Image icon = 1;</code>
     */
    protected $icon = null;
    /**
     * Generated from protobuf field <code>int64 iconDiamond = 2;</code>
     */
    protected $iconDiamond = 0;
    /**
     * Generated from protobuf field <code>int64 level = 3;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>string levelStr = 4;</code>
     */
    protected $levelStr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\Image $icon
     *     @type int|string $iconDiamond
     *     @type int|string $level
     *     @type string $levelStr
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image icon = 1;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getIcon()
    {
        return $this->icon;
    }

    public function hasIcon()
    {
        return isset($this->icon);
    }

    public function clearIcon()
    {
        unset($this->icon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image icon = 1;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 iconDiamond = 2;</code>
     * @return int|string
     */
    public function getIconDiamond()
    {
        return $this->iconDiamond;
    }

    /**
     * Generated from protobuf field <code>int64 iconDiamond = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIconDiamond($var)
    {
        GPBUtil::checkInt64($var);
        $this->iconDiamond = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 level = 3;</code>
     * @return int|string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int64 level = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string levelStr = 4;</code>
     * @return string
     */
    public function getLevelStr()
    {
        return $this->levelStr;
    }

    /**
     * Generated from protobuf field <code>string levelStr = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLevelStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->levelStr = $var;

        return $this;
    }

}

