<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.kk</code>
 */
class kk extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 k = 14;</code>
     */
    protected $k = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $k
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 k = 14;</code>
     * @return int
     */
    public function getK()
    {
        return $this->k;
    }

    /**
     * Generated from protobuf field <code>uint32 k = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setK($var)
    {
        GPBUtil::checkUint32($var);
        $this->k = $var;

        return $this;
    }

}

