<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.NinePatchSetting</code>
 */
class NinePatchSetting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string settingListList = 1;</code>
     */
    private $settingListList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $settingListList
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string settingListList = 1;</code>
     * @return RepeatedField<string>
     */
    public function getSettingListList()
    {
        return $this->settingListList;
    }

    /**
     * Generated from protobuf field <code>repeated string settingListList = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSettingListList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->settingListList = $arr;

        return $this;
    }

}

