<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.PayGrade</code>
 */
class PayGrade extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 totalDiamondCount = 1;</code>
     */
    protected $totalDiamondCount = 0;
    /**
     * Generated from protobuf field <code>.douyin.Image diamondIcon = 2;</code>
     */
    protected $diamondIcon = null;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.douyin.Image icon = 4;</code>
     */
    protected $icon = null;
    /**
     * Generated from protobuf field <code>string nextName = 5;</code>
     */
    protected $nextName = '';
    /**
     * Generated from protobuf field <code>int64 level = 6;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>.douyin.Image nextIcon = 7;</code>
     */
    protected $nextIcon = null;
    /**
     * Generated from protobuf field <code>int64 nextDiamond = 8;</code>
     */
    protected $nextDiamond = 0;
    /**
     * Generated from protobuf field <code>int64 nowDiamond = 9;</code>
     */
    protected $nowDiamond = 0;
    /**
     * Generated from protobuf field <code>int64 thisGradeMinDiamond = 10;</code>
     */
    protected $thisGradeMinDiamond = 0;
    /**
     * Generated from protobuf field <code>int64 thisGradeMaxDiamond = 11;</code>
     */
    protected $thisGradeMaxDiamond = 0;
    /**
     * Generated from protobuf field <code>int64 payDiamondBak = 12;</code>
     */
    protected $payDiamondBak = 0;
    /**
     * Generated from protobuf field <code>string gradeDescribe = 13;</code>
     */
    protected $gradeDescribe = '';
    /**
     * Generated from protobuf field <code>repeated .douyin.GradeIcon gradeIconList = 14;</code>
     */
    private $gradeIconList;
    /**
     * Generated from protobuf field <code>int64 screenChatType = 15;</code>
     */
    protected $screenChatType = 0;
    /**
     * Generated from protobuf field <code>.douyin.Image imIcon = 16;</code>
     */
    protected $imIcon = null;
    /**
     * Generated from protobuf field <code>.douyin.Image imIconWithLevel = 17;</code>
     */
    protected $imIconWithLevel = null;
    /**
     * Generated from protobuf field <code>.douyin.Image liveIcon = 18;</code>
     */
    protected $liveIcon = null;
    /**
     * Generated from protobuf field <code>.douyin.Image newImIconWithLevel = 19;</code>
     */
    protected $newImIconWithLevel = null;
    /**
     * Generated from protobuf field <code>.douyin.Image newLiveIcon = 20;</code>
     */
    protected $newLiveIcon = null;
    /**
     * Generated from protobuf field <code>int64 upgradeNeedConsume = 21;</code>
     */
    protected $upgradeNeedConsume = 0;
    /**
     * Generated from protobuf field <code>string nextPrivileges = 22;</code>
     */
    protected $nextPrivileges = '';
    /**
     * Generated from protobuf field <code>.douyin.Image background = 23;</code>
     */
    protected $background = null;
    /**
     * Generated from protobuf field <code>.douyin.Image backgroundBack = 24;</code>
     */
    protected $backgroundBack = null;
    /**
     * Generated from protobuf field <code>int64 score = 25;</code>
     */
    protected $score = 0;
    /**
     * Generated from protobuf field <code>.douyin.GradeBuffInfo buffInfo = 26;</code>
     */
    protected $buffInfo = null;
    /**
     * Generated from protobuf field <code>string gradeBanner = 1001;</code>
     */
    protected $gradeBanner = '';
    /**
     * Generated from protobuf field <code>.douyin.Image profileDialogBg = 1002;</code>
     */
    protected $profileDialogBg = null;
    /**
     * Generated from protobuf field <code>.douyin.Image profileDialogBgBack = 1003;</code>
     */
    protected $profileDialogBgBack = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $totalDiamondCount
     *     @type \app\protobuf\douyin\Image $diamondIcon
     *     @type string $name
     *     @type \app\protobuf\douyin\Image $icon
     *     @type string $nextName
     *     @type int|string $level
     *     @type \app\protobuf\douyin\Image $nextIcon
     *     @type int|string $nextDiamond
     *     @type int|string $nowDiamond
     *     @type int|string $thisGradeMinDiamond
     *     @type int|string $thisGradeMaxDiamond
     *     @type int|string $payDiamondBak
     *     @type string $gradeDescribe
     *     @type \app\protobuf\douyin\GradeIcon[] $gradeIconList
     *     @type int|string $screenChatType
     *     @type \app\protobuf\douyin\Image $imIcon
     *     @type \app\protobuf\douyin\Image $imIconWithLevel
     *     @type \app\protobuf\douyin\Image $liveIcon
     *     @type \app\protobuf\douyin\Image $newImIconWithLevel
     *     @type \app\protobuf\douyin\Image $newLiveIcon
     *     @type int|string $upgradeNeedConsume
     *     @type string $nextPrivileges
     *     @type \app\protobuf\douyin\Image $background
     *     @type \app\protobuf\douyin\Image $backgroundBack
     *     @type int|string $score
     *     @type \app\protobuf\douyin\GradeBuffInfo $buffInfo
     *     @type string $gradeBanner
     *     @type \app\protobuf\douyin\Image $profileDialogBg
     *     @type \app\protobuf\douyin\Image $profileDialogBgBack
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 totalDiamondCount = 1;</code>
     * @return int|string
     */
    public function getTotalDiamondCount()
    {
        return $this->totalDiamondCount;
    }

    /**
     * Generated from protobuf field <code>int64 totalDiamondCount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalDiamondCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalDiamondCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image diamondIcon = 2;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getDiamondIcon()
    {
        return $this->diamondIcon;
    }

    public function hasDiamondIcon()
    {
        return isset($this->diamondIcon);
    }

    public function clearDiamondIcon()
    {
        unset($this->diamondIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image diamondIcon = 2;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setDiamondIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->diamondIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image icon = 4;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getIcon()
    {
        return $this->icon;
    }

    public function hasIcon()
    {
        return isset($this->icon);
    }

    public function clearIcon()
    {
        unset($this->icon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image icon = 4;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nextName = 5;</code>
     * @return string
     */
    public function getNextName()
    {
        return $this->nextName;
    }

    /**
     * Generated from protobuf field <code>string nextName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNextName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nextName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 level = 6;</code>
     * @return int|string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int64 level = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image nextIcon = 7;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getNextIcon()
    {
        return $this->nextIcon;
    }

    public function hasNextIcon()
    {
        return isset($this->nextIcon);
    }

    public function clearNextIcon()
    {
        unset($this->nextIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image nextIcon = 7;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setNextIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->nextIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nextDiamond = 8;</code>
     * @return int|string
     */
    public function getNextDiamond()
    {
        return $this->nextDiamond;
    }

    /**
     * Generated from protobuf field <code>int64 nextDiamond = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNextDiamond($var)
    {
        GPBUtil::checkInt64($var);
        $this->nextDiamond = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nowDiamond = 9;</code>
     * @return int|string
     */
    public function getNowDiamond()
    {
        return $this->nowDiamond;
    }

    /**
     * Generated from protobuf field <code>int64 nowDiamond = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNowDiamond($var)
    {
        GPBUtil::checkInt64($var);
        $this->nowDiamond = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 thisGradeMinDiamond = 10;</code>
     * @return int|string
     */
    public function getThisGradeMinDiamond()
    {
        return $this->thisGradeMinDiamond;
    }

    /**
     * Generated from protobuf field <code>int64 thisGradeMinDiamond = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setThisGradeMinDiamond($var)
    {
        GPBUtil::checkInt64($var);
        $this->thisGradeMinDiamond = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 thisGradeMaxDiamond = 11;</code>
     * @return int|string
     */
    public function getThisGradeMaxDiamond()
    {
        return $this->thisGradeMaxDiamond;
    }

    /**
     * Generated from protobuf field <code>int64 thisGradeMaxDiamond = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setThisGradeMaxDiamond($var)
    {
        GPBUtil::checkInt64($var);
        $this->thisGradeMaxDiamond = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 payDiamondBak = 12;</code>
     * @return int|string
     */
    public function getPayDiamondBak()
    {
        return $this->payDiamondBak;
    }

    /**
     * Generated from protobuf field <code>int64 payDiamondBak = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayDiamondBak($var)
    {
        GPBUtil::checkInt64($var);
        $this->payDiamondBak = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gradeDescribe = 13;</code>
     * @return string
     */
    public function getGradeDescribe()
    {
        return $this->gradeDescribe;
    }

    /**
     * Generated from protobuf field <code>string gradeDescribe = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setGradeDescribe($var)
    {
        GPBUtil::checkString($var, True);
        $this->gradeDescribe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.GradeIcon gradeIconList = 14;</code>
     * @return RepeatedField<\app\protobuf\douyin\GradeIcon>
     */
    public function getGradeIconList()
    {
        return $this->gradeIconList;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.GradeIcon gradeIconList = 14;</code>
     * @param \app\protobuf\douyin\GradeIcon[] $var
     * @return $this
     */
    public function setGradeIconList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \app\protobuf\douyin\GradeIcon::class);
        $this->gradeIconList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 screenChatType = 15;</code>
     * @return int|string
     */
    public function getScreenChatType()
    {
        return $this->screenChatType;
    }

    /**
     * Generated from protobuf field <code>int64 screenChatType = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScreenChatType($var)
    {
        GPBUtil::checkInt64($var);
        $this->screenChatType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image imIcon = 16;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getImIcon()
    {
        return $this->imIcon;
    }

    public function hasImIcon()
    {
        return isset($this->imIcon);
    }

    public function clearImIcon()
    {
        unset($this->imIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image imIcon = 16;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setImIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->imIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image imIconWithLevel = 17;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getImIconWithLevel()
    {
        return $this->imIconWithLevel;
    }

    public function hasImIconWithLevel()
    {
        return isset($this->imIconWithLevel);
    }

    public function clearImIconWithLevel()
    {
        unset($this->imIconWithLevel);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image imIconWithLevel = 17;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setImIconWithLevel($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->imIconWithLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image liveIcon = 18;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getLiveIcon()
    {
        return $this->liveIcon;
    }

    public function hasLiveIcon()
    {
        return isset($this->liveIcon);
    }

    public function clearLiveIcon()
    {
        unset($this->liveIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image liveIcon = 18;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setLiveIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->liveIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image newImIconWithLevel = 19;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getNewImIconWithLevel()
    {
        return $this->newImIconWithLevel;
    }

    public function hasNewImIconWithLevel()
    {
        return isset($this->newImIconWithLevel);
    }

    public function clearNewImIconWithLevel()
    {
        unset($this->newImIconWithLevel);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image newImIconWithLevel = 19;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setNewImIconWithLevel($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->newImIconWithLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image newLiveIcon = 20;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getNewLiveIcon()
    {
        return $this->newLiveIcon;
    }

    public function hasNewLiveIcon()
    {
        return isset($this->newLiveIcon);
    }

    public function clearNewLiveIcon()
    {
        unset($this->newLiveIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image newLiveIcon = 20;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setNewLiveIcon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->newLiveIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 upgradeNeedConsume = 21;</code>
     * @return int|string
     */
    public function getUpgradeNeedConsume()
    {
        return $this->upgradeNeedConsume;
    }

    /**
     * Generated from protobuf field <code>int64 upgradeNeedConsume = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpgradeNeedConsume($var)
    {
        GPBUtil::checkInt64($var);
        $this->upgradeNeedConsume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nextPrivileges = 22;</code>
     * @return string
     */
    public function getNextPrivileges()
    {
        return $this->nextPrivileges;
    }

    /**
     * Generated from protobuf field <code>string nextPrivileges = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPrivileges($var)
    {
        GPBUtil::checkString($var, True);
        $this->nextPrivileges = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image background = 23;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getBackground()
    {
        return $this->background;
    }

    public function hasBackground()
    {
        return isset($this->background);
    }

    public function clearBackground()
    {
        unset($this->background);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image background = 23;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setBackground($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->background = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundBack = 24;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getBackgroundBack()
    {
        return $this->backgroundBack;
    }

    public function hasBackgroundBack()
    {
        return isset($this->backgroundBack);
    }

    public function clearBackgroundBack()
    {
        unset($this->backgroundBack);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundBack = 24;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setBackgroundBack($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->backgroundBack = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 score = 25;</code>
     * @return int|string
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>int64 score = 25;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt64($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.GradeBuffInfo buffInfo = 26;</code>
     * @return \app\protobuf\douyin\GradeBuffInfo|null
     */
    public function getBuffInfo()
    {
        return $this->buffInfo;
    }

    public function hasBuffInfo()
    {
        return isset($this->buffInfo);
    }

    public function clearBuffInfo()
    {
        unset($this->buffInfo);
    }

    /**
     * Generated from protobuf field <code>.douyin.GradeBuffInfo buffInfo = 26;</code>
     * @param \app\protobuf\douyin\GradeBuffInfo $var
     * @return $this
     */
    public function setBuffInfo($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\GradeBuffInfo::class);
        $this->buffInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gradeBanner = 1001;</code>
     * @return string
     */
    public function getGradeBanner()
    {
        return $this->gradeBanner;
    }

    /**
     * Generated from protobuf field <code>string gradeBanner = 1001;</code>
     * @param string $var
     * @return $this
     */
    public function setGradeBanner($var)
    {
        GPBUtil::checkString($var, True);
        $this->gradeBanner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image profileDialogBg = 1002;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getProfileDialogBg()
    {
        return $this->profileDialogBg;
    }

    public function hasProfileDialogBg()
    {
        return isset($this->profileDialogBg);
    }

    public function clearProfileDialogBg()
    {
        unset($this->profileDialogBg);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image profileDialogBg = 1002;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setProfileDialogBg($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->profileDialogBg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image profileDialogBgBack = 1003;</code>
     * @return \app\protobuf\douyin\Image|null
     */
    public function getProfileDialogBgBack()
    {
        return $this->profileDialogBgBack;
    }

    public function hasProfileDialogBgBack()
    {
        return isset($this->profileDialogBgBack);
    }

    public function clearProfileDialogBgBack()
    {
        unset($this->profileDialogBgBack);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image profileDialogBgBack = 1003;</code>
     * @param \app\protobuf\douyin\Image $var
     * @return $this
     */
    public function setProfileDialogBgBack($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Image::class);
        $this->profileDialogBgBack = $var;

        return $this;
    }

}

