<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.ProductInfo</code>
 */
class ProductInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 promotionId = 1;</code>
     */
    protected $promotionId = 0;
    /**
     * Generated from protobuf field <code>int32 index = 2;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>repeated int64 targetFlashUidsList = 3;</code>
     */
    private $targetFlashUidsList;
    /**
     * Generated from protobuf field <code>int64 explainType = 4;</code>
     */
    protected $explainType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $promotionId
     *     @type int $index
     *     @type int[]|string[] $targetFlashUidsList
     *     @type int|string $explainType
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 promotionId = 1;</code>
     * @return int|string
     */
    public function getPromotionId()
    {
        return $this->promotionId;
    }

    /**
     * Generated from protobuf field <code>int64 promotionId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPromotionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->promotionId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 index = 2;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int32 index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 targetFlashUidsList = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getTargetFlashUidsList()
    {
        return $this->targetFlashUidsList;
    }

    /**
     * Generated from protobuf field <code>repeated int64 targetFlashUidsList = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setTargetFlashUidsList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->targetFlashUidsList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 explainType = 4;</code>
     * @return int|string
     */
    public function getExplainType()
    {
        return $this->explainType;
    }

    /**
     * Generated from protobuf field <code>int64 explainType = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExplainType($var)
    {
        GPBUtil::checkInt64($var);
        $this->explainType = $var;

        return $this;
    }

}

