<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomRankMessage.proto
 * 直播间排行榜
 *
 * Generated from protobuf message <code>douyin.RoomRankMessage</code>
 */
class RoomRankMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>repeated .douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     */
    private $ranksList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\Common $common
     *     @type \app\protobuf\douyin\RoomRankMessage\RoomRank[] $ranksList
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \app\protobuf\douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \app\protobuf\douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     * @return RepeatedField<\app\protobuf\douyin\RoomRankMessage\RoomRank>
     */
    public function getRanksList()
    {
        return $this->ranksList;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.RoomRankMessage.RoomRank ranksList = 2;</code>
     * @param \app\protobuf\douyin\RoomRankMessage\RoomRank[] $var
     * @return $this
     */
    public function setRanksList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \app\protobuf\douyin\RoomRankMessage\RoomRank::class);
        $this->ranksList = $arr;

        return $this;
    }

}

