<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * from https://github.com/jwwsjlm/douyinLive/tree/main/protobuf/douyin.proto
 *
 * Generated from protobuf message <code>douyin.RoomStreamAdaptationMessage</code>
 */
class RoomStreamAdaptationMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>int32 adaptationType = 2;</code>
     */
    protected $adaptationType = 0;
    /**
     * Generated from protobuf field <code>float adaptationHeightRatio = 3;</code>
     */
    protected $adaptationHeightRatio = 0.0;
    /**
     * Generated from protobuf field <code>float adaptationBodyCenterRatio = 4;</code>
     */
    protected $adaptationBodyCenterRatio = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\Common $common
     *     @type int $adaptationType
     *     @type float $adaptationHeightRatio
     *     @type float $adaptationBodyCenterRatio
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \app\protobuf\douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \app\protobuf\douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 adaptationType = 2;</code>
     * @return int
     */
    public function getAdaptationType()
    {
        return $this->adaptationType;
    }

    /**
     * Generated from protobuf field <code>int32 adaptationType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAdaptationType($var)
    {
        GPBUtil::checkInt32($var);
        $this->adaptationType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float adaptationHeightRatio = 3;</code>
     * @return float
     */
    public function getAdaptationHeightRatio()
    {
        return $this->adaptationHeightRatio;
    }

    /**
     * Generated from protobuf field <code>float adaptationHeightRatio = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAdaptationHeightRatio($var)
    {
        GPBUtil::checkFloat($var);
        $this->adaptationHeightRatio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float adaptationBodyCenterRatio = 4;</code>
     * @return float
     */
    public function getAdaptationBodyCenterRatio()
    {
        return $this->adaptationBodyCenterRatio;
    }

    /**
     * Generated from protobuf field <code>float adaptationBodyCenterRatio = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAdaptationBodyCenterRatio($var)
    {
        GPBUtil::checkFloat($var);
        $this->adaptationBodyCenterRatio = $var;

        return $this;
    }

}

