<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use UnexpectedValueException;

/**
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomMsgTypeEnum.proto
 *
 * Protobuf type <code>douyin.RoomMsgTypeEnum</code>
 */
class RoomMsgTypeEnum
{
    /**
     * Generated from protobuf enum <code>DEFAULTROOMMSG = 0;</code>
     */
    const DEFAULTROOMMSG = 0;
    /**
     * Generated from protobuf enum <code>ECOMLIVEREPLAYSAVEROOMMSG = 1;</code>
     */
    const ECOMLIVEREPLAYSAVEROOMMSG = 1;
    /**
     * Generated from protobuf enum <code>CONSUMERRELATIONROOMMSG = 2;</code>
     */
    const CONSUMERRELATIONROOMMSG = 2;
    /**
     * Generated from protobuf enum <code>JUMANJIDATAAUTHNOTIFYMSG = 3;</code>
     */
    const JUMANJIDATAAUTHNOTIFYMSG = 3;
    /**
     * Generated from protobuf enum <code>VSWELCOMEMSG = 4;</code>
     */
    const VSWELCOMEMSG = 4;
    /**
     * Generated from protobuf enum <code>MINORREFUNDMSG = 5;</code>
     */
    const MINORREFUNDMSG = 5;
    /**
     * Generated from protobuf enum <code>PAIDLIVEROOMNOTIFYANCHORMSG = 6;</code>
     */
    const PAIDLIVEROOMNOTIFYANCHORMSG = 6;
    /**
     * Generated from protobuf enum <code>HOSTTEAMSYSTEMMSG = 7;</code>
     */
    const HOSTTEAMSYSTEMMSG = 7;

    private static $valueToName = [
        self::DEFAULTROOMMSG => 'DEFAULTROOMMSG',
        self::ECOMLIVEREPLAYSAVEROOMMSG => 'ECOMLIVEREPLAYSAVEROOMMSG',
        self::CONSUMERRELATIONROOMMSG => 'CONSUMERRELATIONROOMMSG',
        self::JUMANJIDATAAUTHNOTIFYMSG => 'JUMANJIDATAAUTHNOTIFYMSG',
        self::VSWELCOMEMSG => 'VSWELCOMEMSG',
        self::MINORREFUNDMSG => 'MINORREFUNDMSG',
        self::PAIDLIVEROOMNOTIFYANCHORMSG => 'PAIDLIVEROOMNOTIFYANCHORMSG',
        self::HOSTTEAMSYSTEMMSG => 'HOSTTEAMSYSTEMMSG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

