<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * from https://github.com/scx567888/live-room-watcher/blob/master/src/main/proto/douyin_hack/webcast/im/RoomMessage.proto
 *
 * Generated from protobuf message <code>douyin.RoomMessage</code>
 */
class RoomMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>string content = 2;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>bool supprotLandscape = 3;</code>
     */
    protected $supprotLandscape = false;
    /**
     * Generated from protobuf field <code>.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
     */
    protected $roommessagetype = 0;
    /**
     * Generated from protobuf field <code>bool systemTopMsg = 5;</code>
     */
    protected $systemTopMsg = false;
    /**
     * Generated from protobuf field <code>bool forcedGuarantee = 6;</code>
     */
    protected $forcedGuarantee = false;
    /**
     * Generated from protobuf field <code>string bizScene = 20;</code>
     */
    protected $bizScene = '';
    /**
     * Generated from protobuf field <code>map<string, string> buriedPointMap = 30;</code>
     */
    private $buriedPointMap;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\Common $common
     *     @type string $content
     *     @type bool $supprotLandscape
     *     @type int $roommessagetype
     *     @type bool $systemTopMsg
     *     @type bool $forcedGuarantee
     *     @type string $bizScene
     *     @type array|\Google\Protobuf\Internal\MapField $buriedPointMap
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \app\protobuf\douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \app\protobuf\douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 2;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool supprotLandscape = 3;</code>
     * @return bool
     */
    public function getSupprotLandscape()
    {
        return $this->supprotLandscape;
    }

    /**
     * Generated from protobuf field <code>bool supprotLandscape = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupprotLandscape($var)
    {
        GPBUtil::checkBool($var);
        $this->supprotLandscape = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
     * @return int
     */
    public function getRoommessagetype()
    {
        return $this->roommessagetype;
    }

    /**
     * Generated from protobuf field <code>.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRoommessagetype($var)
    {
        GPBUtil::checkEnum($var, \app\protobuf\douyin\RoomMsgTypeEnum::class);
        $this->roommessagetype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool systemTopMsg = 5;</code>
     * @return bool
     */
    public function getSystemTopMsg()
    {
        return $this->systemTopMsg;
    }

    /**
     * Generated from protobuf field <code>bool systemTopMsg = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSystemTopMsg($var)
    {
        GPBUtil::checkBool($var);
        $this->systemTopMsg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool forcedGuarantee = 6;</code>
     * @return bool
     */
    public function getForcedGuarantee()
    {
        return $this->forcedGuarantee;
    }

    /**
     * Generated from protobuf field <code>bool forcedGuarantee = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setForcedGuarantee($var)
    {
        GPBUtil::checkBool($var);
        $this->forcedGuarantee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bizScene = 20;</code>
     * @return string
     */
    public function getBizScene()
    {
        return $this->bizScene;
    }

    /**
     * Generated from protobuf field <code>string bizScene = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setBizScene($var)
    {
        GPBUtil::checkString($var, True);
        $this->bizScene = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> buriedPointMap = 30;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getBuriedPointMap()
    {
        return $this->buriedPointMap;
    }

    /**
     * Generated from protobuf field <code>map<string, string> buriedPointMap = 30;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setBuriedPointMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->buriedPointMap = $arr;

        return $this;
    }

}

