<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.TextEffect</code>
 */
class TextEffect extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.TextEffectDetail portrait = 1;</code>
     */
    protected $portrait = null;
    /**
     * Generated from protobuf field <code>.douyin.TextEffectDetail landscape = 2;</code>
     */
    protected $landscape = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\TextEffectDetail $portrait
     *     @type \app\protobuf\douyin\TextEffectDetail $landscape
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.TextEffectDetail portrait = 1;</code>
     * @return \app\protobuf\douyin\TextEffectDetail|null
     */
    public function getPortrait()
    {
        return $this->portrait;
    }

    public function hasPortrait()
    {
        return isset($this->portrait);
    }

    public function clearPortrait()
    {
        unset($this->portrait);
    }

    /**
     * Generated from protobuf field <code>.douyin.TextEffectDetail portrait = 1;</code>
     * @param \app\protobuf\douyin\TextEffectDetail $var
     * @return $this
     */
    public function setPortrait($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\TextEffectDetail::class);
        $this->portrait = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.TextEffectDetail landscape = 2;</code>
     * @return \app\protobuf\douyin\TextEffectDetail|null
     */
    public function getLandscape()
    {
        return $this->landscape;
    }

    public function hasLandscape()
    {
        return isset($this->landscape);
    }

    public function clearLandscape()
    {
        unset($this->landscape);
    }

    /**
     * Generated from protobuf field <code>.douyin.TextEffectDetail landscape = 2;</code>
     * @param \app\protobuf\douyin\TextEffectDetail $var
     * @return $this
     */
    public function setLandscape($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\TextEffectDetail::class);
        $this->landscape = $var;

        return $this;
    }

}

