<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: douyin.proto

namespace app\protobuf\douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>douyin.TextPieceUser</code>
 */
class TextPieceUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.User user = 1;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>bool withColon = 2;</code>
     */
    protected $withColon = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \app\protobuf\douyin\User $user
     *     @type bool $withColon
     * }
     */
    public function __construct($data = NULL) {
        \app\protobuf\GPBMetadata\Douyin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 1;</code>
     * @return \app\protobuf\douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 1;</code>
     * @param \app\protobuf\douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \app\protobuf\douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool withColon = 2;</code>
     * @return bool
     */
    public function getWithColon()
    {
        return $this->withColon;
    }

    /**
     * Generated from protobuf field <code>bool withColon = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setWithColon($var)
    {
        GPBUtil::checkBool($var);
        $this->withColon = $var;

        return $this;
    }

}

